### ISSUE TITLE
analyze.py fails on networkx

### ISSUE THREAD

**Issue by jameslamb** [jameslamb/doppel-cli#72]
Running

```
doppel-describe -l python -p networkx -d $(pwd)
```

Yields:

```
Testing package networkx [python]
/Users/jlamb/Library/Caches/Python-Eggs/doppel_cli-0.1.7-py3.6.egg-tmp/doppel/bin/analyze.py
Describing package with command:
 /Users/jlamb/Library/Caches/Python-Eggs/doppel_cli-0.1.7-py3.6.egg-tmp/doppel/bin/analyze.py --pkg networkx --output_dir /Users/jlamb/repos/doppel-cli --kwargs-string ~~KWARGS~~ --constructor-string ~~CONSTRUCTOR~~
AmbiguousSolution is an Exception. Skipping.
'DiGraph' is a class in this package, adding it
Traceback (most recent call last):
  File "/Users/jlamb/anaconda3/lib/python3.6/inspect.py", line 1119, in getfullargspec
    sigcls=Signature)
  File "/Users/jlamb/anaconda3/lib/python3.6/inspect.py", line 2342, in _signature_from_callable
    'no signature found for builtin type {!r}'.format(obj))
```

No idea if this is specific to something weird that `networkx` does or some broader gap in `doppel-cli` functionality. Deserves some investigation!

**Comment by jameslamb** [comment]
Closing this as a duplicate of #78 . That issue is the newer one and has better documentation of the problem.
